# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d19ded912ee552dbdfe1ff6824a85ac7e753405a7f7bf46cdffe9fefef41562b08337bb121611aa68a44251a7f44f9a150b7c52d10235fd4d7aeb79a81666c

test:
  secret_key_base: f7178643587f07fe23adf68c369401628e77367a6ab9661fd4e49b02c1fa43f413885f0e7fee1bfc9588d7dad281b7971ac8e1073aff03f82d532c32b72e7d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
